<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MUL3" Id="{a7bc8c9c-4397-486a-a62a-b4f742da07ae}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MUL3 : REAL
VAR_INPUT
	in1 : REAL;
	in2 : REAL;
	in3 : REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MUL3 := in1 * in2 * in3;]]></ST>
    </Implementation>
    <LineIds Name="MUL3">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>